### ISSUE TITLE
load_cifar_data.py, line 29 error

### ISSUE THREAD

**Issue by xukai504087493** [banana-peel/Population-Based-Training-of-ResNet-for-CIFAR10#1]
load_cifar_data.py", line 29, in load_data_from_file
    inp_data = pickle.load(f, encoding='latin1')
TypeError: load() takes no keyword arguments
How to solve this error? since I have already downloading "cifar-10-batches-py" data sets. Thank you!

**Comment by banana-peel** [comment]
change the line to inp_data = pickle.load(f). It should work now.
Btw, which version of python are you using?
